grussfabrik.com/Controllers/ContactUsController.cs
using grussfabrik.Models;
using System;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;

namespace grussfabrik.Controllers
{
    public class ContactUsController : Controller
    {

        public JsonResult SendEMail(EmailModel model)
        {
            //var mailSever = "smtp.gmail.com";
            //var mailSeverPort = 587;
            //var senderMailAddress = "any@gmail.com";
            //var adminMail = "satyanamsoft@gmail.com";
            //var userId = "satyanamsoft@gmail.com";

            var mailSever = "email-smtp.eu-west-1.amazonaws.com";
            var senderMailAddress = "info@kugelschreiberdruck.de";
            var adminMail = "info@kugelschreiberdruck.de";
            var userId = "AKIAJ47HFFDQRZVTSEJQ";

            var password = string.Empty;
            bool isMailSent = false;
            string erorrMessage = string.Empty;
            if (ModelState.IsValid)
            {
                try
                {
                    //var client = new SmtpClient(mailSever, mailSeverPort);
                    var client = new SmtpClient(mailSever);
                    client.Credentials = new NetworkCredential(userId, password);
                    MailMessage mailMessage = new MailMessage();
                    mailMessage.From = new MailAddress(senderMailAddress);
                    mailMessage.To.Add(adminMail);
                    mailMessage.Body = model.Body;
                    client.Send(mailMessage);
                }
                catch (Exception ex)
                {
                    isMailSent = false;
                    erorrMessage = $"Failed sending mail: {ex.Message}";
                }
            }
            return Json(new { success = isMailSent, erorr = erorrMessage });
        }

    }
}

grussfabrik.com/Views/Shared/_ContactUs.cshtml
<section class="row">
    <img class="col-sm-6 col-xs-11 pull-right contact-model" src="~/Content/Images/Home/contact-us.png" />
    <div class="container">
        <article class="col-sm-6 col-xs-12 contact-content pull-left">
            <h2 id="contactus">Kontaktieren Sie Uns</h2>
            <div class="form-container">
                <form id="form_contact_us">
                    <div class="form-group">
                        <input type="text" class="form-control" id="FullName" name="FullName" placeholder="Ihr Name" required>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" id="UserEmail" name="UserEmail" placeholder="Ihre Email" data-fv-emailaddress-message="Invalid email address" required>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" type="textarea" id="Body" name="Body" placeholder="Ihre Nachricht an uns" rows="7" required></textarea>
                    </div>
                    <button type="submit" id="Send" class="btn btn-default">ANFRAGE SENDEN</button>
                </form>
            </div>
        </article>
    </div>
</section>

<script>
window.onload = function () {
    var $ = jQuery;
    function SendMail() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("SendEMail", "ContactUs")',
            data: $('#form_contact_us').serialize(),
            dataType: "json",
            success: function (result) {
                (result.success) ? success() : error(result.erorr);
            },
            erorr: error,
        });

        var success = function () {
            alert('Your enquiry has been sent successfully...')
            $('#FullName, #UserEmail, #Body').val("");
        };
        var error = function (msg) {
            alert('Something went wrong...')
            console.log(msg);
        };
    }

    $("#form_contact_us").on("submit", function () {
        SendMail();
        return false;
    })
}
</script>

grussfabrik.com/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-white navbar-fixed-top" id="scroll_tracker">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand logo js-scroll-trigger" href="#home">
                    <img src="~/Content/Images/logo.png" style="display: inline-block;">
                </a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#aboutus">Über Uns</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#websites">Unsere Webseiten</a>
                    </li>
                    @*<li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#team">Team</a>
                    </li>*@
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contactus">Kontakt</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="body-content">
        @RenderBody()
        <footer class="container">
        <hr />
            <div class="row footer-content">
                <section class="col-xs-6 about-info">
                    <strong>Über Uns</strong>
                    <p>
                        Wir sind ein Multi-Shop-Unternehmen mit Sitz in Zürich. Unsere Produkte sind so vielfältig wie Ihre
                        Wünsche: ob Wein, Ballon, Kugelschreiber oder Fahne, wir haben es verfügbar und liefern schnell
                        und zuverlässig zu einem überzeugenden Preis-Leistungs-Verhältnis.
                    </p>
                </section>
                <section class="col-xs-6">
                    <article class="col-xs-4 site-map">
                        <strong>Links</strong>
                        <p> <a class="js-scroll-trigger" href="#home">Home</a></p>
                        <p> <a class="js-scroll-trigger" href="#aboutus">Über Uns</a></p>
                        <p> <a class="js-scroll-trigger" href="#websites">Unsere Webseiten</a></p>
                        @*<p> <a class="js-scroll-trigger" href="#team">Team</a></p>*@
                        <p> <a class="js-scroll-trigger" href="#contactus">Kontakt</a></p>
                    </article>
                    <article class="col-xs-4 contact-info">
                        <strong>Kontakt</strong>
                        <p>grussfabrik.ch AG</p>
                        <p>Talacker 50</p>
                        <p>8001 Zürich </p>
                        <p>Schweiz</p>
                        <div class="contact-hl">
                            <p>+41 44 522 04 36</p>
                            <p>info@grussfabrik.ch</p>
                        </div>
                    </article>
                </section>
            </div>
            <section class="copyright">
                <aside class="footer-logo pull-left">
                    <img src="~/Content/Images/logo.png" />
                </aside>
                <aside class="pull-right">
                    <p class="copyright-content">© 2017-2018 Grussfabrik.ch. All Rights Reserved.</p>
                </aside>
            </section>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/popper/popper.min.js")
    @Scripts.Render("~/Scripts/jquery-easing/jquery.easing.min.js")
    @Scripts.Render("~/Scripts/jquery-easing/jquery.easing.compatibility.js")
    @Scripts.Render("~/Scripts/scrolling-nav.js")
    @RenderSection("scripts", required: false)
</body>
</html>